/* ==========================================================================
   The Goblin's Guide — curated dataset of notable London pubs & bars.
   Coordinates are approximate. Ratings (out of 5) are a blend of public
   review reputation and beer-guide acclaim; keywords are distilled from
   the things reviewers mention most.
   ========================================================================== */

const PUBS = [
  // ---- Soho / Covent Garden / West End ----
  { name: "The French House", type: "pub", area: "Soho", lat: 51.5133, lng: -0.1317, rating: 4.6,
    keywords: ["half pints only", "bohemian", "no phones", "history"],
    desc: "Soho legend where De Gaulle drank and phones are banned. Beer comes in halves — deal with it." },
  { name: "The Harp", type: "pub", area: "Covent Garden", lat: 51.5095, lng: -0.1265, rating: 4.7,
    keywords: ["cask ale", "perfect pint", "narrow & packed", "sausages"],
    desc: "Multiple-award-winning ale house. Tiny, glorious, and pouring some of the best cask in London." },
  { name: "The Lamb & Flag", type: "pub", area: "Covent Garden", lat: 51.5116, lng: -0.1264, rating: 4.5,
    keywords: ["1623 vintage", "Dickens drank here", "alleyway", "cosy"],
    desc: "Covent Garden's oldest boozer, tucked down an alley once known for bare-knuckle fights." },
  { name: "The Dog and Duck", type: "pub", area: "Soho", lat: 51.5142, lng: -0.1322, rating: 4.4,
    keywords: ["Victorian tiles", "Orwell's local", "tiny", "cask ale"],
    desc: "A jewel-box of glazed tiles and mirrors. George Orwell celebrated Animal Farm here." },
  { name: "The Coach & Horses", type: "pub", area: "Soho", lat: 51.5136, lng: -0.1309, rating: 4.3,
    keywords: ["Soho institution", "eccentric", "pie & mash", "sing-alongs"],
    desc: "Private Eye's long-time canteen; famously London's rudest landlord, now merely mischievous." },
  { name: "The Salisbury", type: "pub", area: "Covent Garden", lat: 51.5107, lng: -0.1276, rating: 4.4,
    keywords: ["etched glass", "Victorian glamour", "theatreland", "gin"],
    desc: "Cut-glass and gilt everywhere you look — the West End's most theatrical pub interior." },
  { name: "The Cross Keys", type: "pub", area: "Covent Garden", lat: 51.5147, lng: -0.1247, rating: 4.4,
    keywords: ["brass & foliage", "characterful", "proper boozer"],
    desc: "Front smothered in greenery, inside smothered in brass. A proper pub amid the tourist swirl." },
  { name: "The Ship & Shovell", type: "pub", area: "Charing Cross", lat: 51.5077, lng: -0.1247, rating: 4.4,
    keywords: ["two halves", "split by alley", "Badger ales", "quirky"],
    desc: "The only pub in London in two halves, facing each other across a Victorian passage." },
  { name: "The Sherlock Holmes", type: "pub", area: "Charing Cross", lat: 51.5069, lng: -0.1244, rating: 4.1,
    keywords: ["memorabilia", "touristy", "fun", "fish & chips"],
    desc: "Shameless but charming Holmes shrine, complete with a recreation of 221B upstairs." },
  { name: "The Argyll Arms", type: "pub", area: "Oxford Circus", lat: 51.5152, lng: -0.1409, rating: 4.3,
    keywords: ["snob screens", "Victorian", "shopping refuge", "cask ale"],
    desc: "Ornate 1860s snug screens survive intact — a miracle 30 seconds from Oxford Circus." },
  { name: "Swift", type: "bar", area: "Soho", lat: 51.5136, lng: -0.1312, rating: 4.5,
    keywords: ["cocktails", "irish coffee", "upstairs quick, downstairs slow"],
    desc: "Quick drinks and oysters upstairs, dark whisky den below. One of Soho's best bars." },
  { name: "Bar Termini", type: "bar", area: "Soho", lat: 51.5134, lng: -0.1310, rating: 4.4,
    keywords: ["negroni", "espresso", "tiny", "italian"],
    desc: "A shoebox of Italian perfection — pre-bottled negronis and proper espresso." },

  // ---- Mayfair / St James / Westminster / Belgravia ----
  { name: "The Guinea", type: "pub", area: "Mayfair", lat: 51.5106, lng: -0.1477, rating: 4.4,
    keywords: ["steak & grill", "mews pub", "Youngs", "old money"],
    desc: "A 1720s mews pub hiding one of London's great grill rooms behind the bar." },
  { name: "The Red Lion (Duke of York St)", type: "pub", area: "St James's", lat: 51.5081, lng: -0.1370, rating: 4.4,
    keywords: ["mirrored gem", "mahogany", "tiny", "gentlemanly"],
    desc: "A tiny mirrored jewel — possibly the most perfect small Victorian pub interior in London." },
  { name: "The Red Lion (Westminster)", type: "pub", area: "Westminster", lat: 51.5010, lng: -0.1263, rating: 4.1,
    keywords: ["division bell", "politicians", "history"],
    desc: "Between Downing Street and Parliament; has poured for every PM since Walpole, allegedly." },
  { name: "The Grenadier", type: "pub", area: "Belgravia", lat: 51.5013, lng: -0.1560, rating: 4.4,
    keywords: ["haunted", "hidden mews", "bloody mary", "military"],
    desc: "Hidden in a cobbled mews and supposedly haunted by a card-cheating soldier. Great Bloody Mary." },
  { name: "The Nags Head", type: "pub", area: "Belgravia", lat: 51.5019, lng: -0.1567, rating: 4.5,
    keywords: ["no phones", "low bar", "eccentric", "trinkets"],
    desc: "Phone use banned, ceilings low, walls chaotic with curios. A stubborn, brilliant time capsule." },
  { name: "The Star Tavern", type: "pub", area: "Belgravia", lat: 51.4996, lng: -0.1553, rating: 4.6,
    keywords: ["Fuller's", "Great Train Robbery", "open fire", "mews"],
    desc: "Where the Great Train Robbery was allegedly planned. In every Good Beer Guide ever printed." },
  { name: "The Buckingham Arms", type: "pub", area: "Westminster", lat: 51.4995, lng: -0.1345, rating: 4.3,
    keywords: ["Youngs", "long bar", "civilised", "cask ale"],
    desc: "A gracious Young's house near the Palace — another Good Beer Guide ever-present." },
  { name: "The Morpeth Arms", type: "pub", area: "Pimlico", lat: 51.4903, lng: -0.1284, rating: 4.2,
    keywords: ["spy views", "haunted cells", "riverside", "Youngs"],
    desc: "Face the MI6 building with a pint; prisoners' cells (and a ghost) linger below." },
  { name: "The Cask", type: "pub", area: "Pimlico", lat: 51.4894, lng: -0.1354, rating: 4.5,
    keywords: ["craft beer", "huge fridge list", "beer geek heaven"],
    desc: "Unassuming looks, encyclopaedic beer list. A pilgrimage spot for hopheads." },

  // ---- Fitzrovia / Bloomsbury / Marylebone ----
  { name: "The Fitzroy Tavern", type: "pub", area: "Fitzrovia", lat: 51.5181, lng: -0.1348, rating: 4.2,
    keywords: ["Sam Smith's", "cheap pints", "literary", "Dylan Thomas"],
    desc: "Gave Fitzrovia its name; Dylan Thomas and Orwell propped up this bar." },
  { name: "The Newman Arms", type: "pub", area: "Fitzrovia", lat: 51.5187, lng: -0.1349, rating: 4.2,
    keywords: ["pie room", "Orwell", "tiny", "candlelit"],
    desc: "Famous pies upstairs in a pub Orwell wrote into Nineteen Eighty-Four." },
  { name: "The Champion", type: "pub", area: "Fitzrovia", lat: 51.5168, lng: -0.1381, rating: 4.3,
    keywords: ["stained glass", "Sam Smith's", "Victorian heroes"],
    desc: "Stained-glass windows celebrate Victorian champions — boxers, cricketers, aviators." },
  { name: "The Lamb", type: "pub", area: "Bloomsbury", lat: 51.5222, lng: -0.1180, rating: 4.5,
    keywords: ["snob screens", "Youngs", "Dickens", "polished wood"],
    desc: "Pivoting snob screens still circle the bar of this immaculate 1720s Bloomsbury treasure." },
  { name: "The Museum Tavern", type: "pub", area: "Bloomsbury", lat: 51.5183, lng: -0.1266, rating: 4.3,
    keywords: ["opposite British Museum", "Karl Marx drank here", "Victorian"],
    desc: "Where Karl Marx allegedly took refreshment after a hard day in the Reading Room." },
  { name: "The Queen's Larder", type: "pub", area: "Bloomsbury", lat: 51.5211, lng: -0.1224, rating: 4.2,
    keywords: ["tiny", "royal history", "garden square"],
    desc: "Queen Charlotte reputedly stored delicacies here for mad King George III." },
  { name: "The Euston Tap", type: "pub", area: "Euston", lat: 51.5277, lng: -0.1330, rating: 4.3,
    keywords: ["craft beer", "gatehouse", "pre-train pint", "tap list"],
    desc: "A stone Victorian gatehouse crammed with taps — the definitive pre-train pint." },
  { name: "The Barley Mow", type: "pub", area: "Marylebone", lat: 51.5205, lng: -0.1554, rating: 4.4,
    keywords: ["pawnbroker booths", "1791", "snug", "cask ale"],
    desc: "Keeps two coffin-like private drinking booths from its 1791 pawnbroker days." },
  { name: "The Golden Eagle", type: "pub", area: "Marylebone", lat: 51.5170, lng: -0.1508, rating: 4.5,
    keywords: ["piano singalong", "old school", "tiny", "gem"],
    desc: "Thrice-weekly piano singalongs in a one-room pub that time forgot." },

  // ---- City / Clerkenwell / Holborn / Fleet Street ----
  { name: "Ye Olde Cheshire Cheese", type: "pub", area: "Fleet Street", lat: 51.5142, lng: -0.1073, rating: 4.4,
    keywords: ["1667 rebuild", "cellars & warrens", "Dickens", "Sam Smith's"],
    desc: "Rebuilt after the Great Fire; a warren of dark rooms where Dickens, Twain and Johnson drank." },
  { name: "Ye Olde Mitre", type: "pub", area: "Hatton Garden", lat: 51.5186, lng: -0.1077, rating: 4.6,
    keywords: ["hardest to find", "1546", "cherry tree", "toasties"],
    desc: "Hidden down an alley off Hatton Garden since 1546. Finding it is half the pleasure." },
  { name: "The Blackfriar", type: "pub", area: "Blackfriars", lat: 51.5121, lng: -0.1035, rating: 4.4,
    keywords: ["art nouveau", "friar carvings", "architectural icon"],
    desc: "An Arts-and-Crafts fever dream of marble and jolly bronze friars. Nothing else like it." },
  { name: "The Viaduct Tavern", type: "pub", area: "St Paul's", lat: 51.5164, lng: -0.1017, rating: 4.2,
    keywords: ["gin palace", "Newgate cells", "haunted"],
    desc: "A surviving Victorian gin palace with what are claimed to be Newgate prison cells below." },
  { name: "The Counting House", type: "pub", area: "Bank", lat: 51.5130, lng: -0.0857, rating: 4.2,
    keywords: ["former bank", "grand dome", "Fuller's", "pies"],
    desc: "A palatial banking hall repurposed for the nobler business of ale and pie." },
  { name: "The Lamb Tavern", type: "pub", area: "Leadenhall", lat: 51.5128, lng: -0.0834, rating: 4.3,
    keywords: ["Leadenhall Market", "Victorian ironwork", "city suits"],
    desc: "Standing proud in Leadenhall's painted ironwork since 1780." },
  { name: "The Jerusalem Tavern", type: "pub", area: "Clerkenwell", lat: 51.5222, lng: -0.1023, rating: 4.6,
    keywords: ["St Peter's ales", "candlelit", "tiny", "18th century"],
    desc: "A dim, creaking 1720s shopfront pouring St Peter's Brewery ales. Utterly transporting." },
  { name: "The Craft Beer Co. Clerkenwell", type: "pub", area: "Clerkenwell", lat: 51.5219, lng: -0.1096, rating: 4.4,
    keywords: ["30+ taps", "craft beer", "mirrored ceiling"],
    desc: "The original of the chain and still the best — a dazzling tap list under a mirrored ceiling." },
  { name: "The Eagle", type: "pub", area: "Farringdon", lat: 51.5238, lng: -0.1104, rating: 4.4,
    keywords: ["first gastropub", "steak sandwich", "open kitchen"],
    desc: "Where the word 'gastropub' was invented in 1991. The bife ana steak sandwich endures." },
  { name: "The Betsey Trotwood", type: "pub", area: "Clerkenwell", lat: 51.5230, lng: -0.1077, rating: 4.3,
    keywords: ["live music", "Dickens name", "friendly"],
    desc: "A cherry-red Clerkenwell favourite with folk and indie gigs in the cellar." },
  { name: "The Cittie of Yorke", type: "pub", area: "Holborn", lat: 51.5177, lng: -0.1123, rating: 4.4,
    keywords: ["cathedral hall", "wooden booths", "Sam Smith's", "vast vats"],
    desc: "A great hall of a pub — soaring roof, giant vats, and confessional drinking booths." },
  { name: "The Princess Louise", type: "pub", area: "Holborn", lat: 51.5170, lng: -0.1206, rating: 4.5,
    keywords: ["Victorian screens", "cheap pints", "Sam Smith's", "listed loos"],
    desc: "The full Victorian works: etched glass, carved screens, and Grade II listed gents'." },
  { name: "The Seven Stars", type: "pub", area: "Holborn", lat: 51.5152, lng: -0.1123, rating: 4.4,
    keywords: ["1602", "pub cat", "lawyers", "eccentric"],
    desc: "Predates the Great Fire; famous for its ruff-wearing pub cats and barrister clientele." },
  { name: "The Old Bank of England", type: "pub", area: "Fleet Street", lat: 51.5139, lng: -0.1119, rating: 4.2,
    keywords: ["opulent hall", "pies", "Sweeney Todd lore"],
    desc: "A gilded former bank hall on the site between Sweeney Todd's barbershop and pie shop. Allegedly." },

  // ---- Borough / Southwark / Bermondsey / Waterloo ----
  { name: "The George Inn", type: "pub", area: "Borough", lat: 51.5040, lng: -0.0899, rating: 4.4,
    keywords: ["galleried coaching inn", "National Trust", "Shakespeare", "courtyard"],
    desc: "London's last galleried coaching inn, minded by the National Trust since 1937." },
  { name: "The Market Porter", type: "pub", area: "Borough Market", lat: 51.5052, lng: -0.0910, rating: 4.4,
    keywords: ["market hours", "rotating casks", "spills onto street"],
    desc: "Opens at dawn for market traders; the ever-changing cask lineup draws the crowds." },
  { name: "The Rake", type: "pub", area: "Borough Market", lat: 51.5055, lng: -0.0906, rating: 4.3,
    keywords: ["tiny", "world beers", "signed walls"],
    desc: "One of London's smallest pubs with one of its biggest beer reputations." },
  { name: "The Anchor Bankside", type: "pub", area: "Bankside", lat: 51.5074, lng: -0.0920, rating: 4.0,
    keywords: ["riverside terrace", "Great Fire views", "touristy"],
    desc: "Pepys watched London burn from here. Now everyone watches the Thames with a pint." },
  { name: "The Lord Clyde", type: "pub", area: "Borough", lat: 51.5019, lng: -0.0938, rating: 4.5,
    keywords: ["tiled facade", "family run", "backstreet gem"],
    desc: "A glorious tiled frontage and a proper family-run welcome, one street from the chaos." },
  { name: "The Royal Oak", type: "pub", area: "Borough", lat: 51.5008, lng: -0.0913, rating: 4.5,
    keywords: ["Harvey's ales", "two bars", "old fashioned"],
    desc: "London's only Harvey's of Lewes pub — sussex ale perfection in a two-bar time warp." },
  { name: "The Mayflower", type: "pub", area: "Rotherhithe", lat: 51.5017, lng: -0.0538, rating: 4.5,
    keywords: ["Pilgrim ship moorings", "jetty over Thames", "candlelit"],
    desc: "The Mayflower set off from this spot in 1620. Drink on the jetty above the tide." },
  { name: "The Angel", type: "pub", area: "Bermondsey", lat: 51.5006, lng: -0.0631, rating: 4.3,
    keywords: ["Sam Smith's", "river views", "balcony"],
    desc: "A lonely riverside survivor with a balcony hanging right over the Thames." },
  { name: "The Garrison", type: "pub", area: "Bermondsey", lat: 51.5007, lng: -0.0819, rating: 4.3,
    keywords: ["gastropub", "brunch", "Bermondsey St"],
    desc: "Pretty, buzzy gastropub anchoring Bermondsey Street's food strip." },
  { name: "The Kings Arms", type: "pub", area: "Waterloo", lat: 51.5043, lng: -0.1088, rating: 4.5,
    keywords: ["Roupell St", "cask ale", "thai food", "conservation street"],
    desc: "On a perfectly preserved Victorian terrace; great cask up front, Thai kitchen out back." },
  { name: "The Anchor & Hope", type: "pub", area: "Waterloo", lat: 51.5031, lng: -0.1076, rating: 4.4,
    keywords: ["legendary food", "no reservations", "gastropub royalty"],
    desc: "One of the gastropubs that defined the genre. Queue for the food; stay for everything else." },

  // ---- Shoreditch / Spitalfields / East ----
  { name: "The Ten Bells", type: "pub", area: "Spitalfields", lat: 51.5197, lng: -0.0746, rating: 4.2,
    keywords: ["Jack the Ripper lore", "Victorian tiles", "atmospheric"],
    desc: "Ripper-era tiles and tales, opposite Spitalfields Market since the 1750s." },
  { name: "The Pride of Spitalfields", type: "pub", area: "Spitalfields", lat: 51.5188, lng: -0.0703, rating: 4.5,
    keywords: ["pub cat", "east end proper", "cosy", "off Brick Lane"],
    desc: "A genuine East End parlour pub one step from Brick Lane. Say hello to the cat." },
  { name: "The Carpenter's Arms", type: "pub", area: "Bethnal Green", lat: 51.5232, lng: -0.0658, rating: 4.5,
    keywords: ["Kray history", "great beer list", "friendly"],
    desc: "Once owned by the Kray twins for their mum; now one of the East End's friendliest beer pubs." },
  { name: "The Marksman", type: "pub", area: "Hackney Road", lat: 51.5301, lng: -0.0616, rating: 4.4,
    keywords: ["Michelin pub food", "brown-wood boozer", "sunday roast"],
    desc: "Looks like your grandad's local, cooks like a Michelin kitchen. Book the roast." },
  { name: "The Old Blue Last", type: "pub", area: "Shoreditch", lat: 51.5238, lng: -0.0819, rating: 4.1,
    keywords: ["live bands", "sticky floors", "young crowd"],
    desc: "Vice's old gig pub; sweaty upstairs shows that occasionally mint the next big thing." },
  { name: "The Owl & Pussycat", type: "pub", area: "Shoreditch", lat: 51.5250, lng: -0.0745, rating: 4.3,
    keywords: ["beer garden", "quiet corner", "pub food"],
    desc: "A calm, wood-panelled refuge with a proper garden amid the Shoreditch din." },
  { name: "The Well & Bucket", type: "pub", area: "Bethnal Green", lat: 51.5238, lng: -0.0713, rating: 4.3,
    keywords: ["tiled walls", "oysters", "craft beer", "skull art"],
    desc: "Victorian tiles meet contemporary art, oysters, and a sharp tap list." },
  { name: "The Wenlock Arms", type: "pub", area: "Hoxton", lat: 51.5310, lng: -0.0917, rating: 4.6,
    keywords: ["cask legend", "saved by campaigners", "open fire", "dogs"],
    desc: "Rescued from developers by its regulars — a true ale-lovers' community pub." },
  { name: "Nightjar", type: "bar", area: "Shoreditch", lat: 51.5265, lng: -0.0876, rating: 4.5,
    keywords: ["speakeasy", "live jazz", "theatrical cocktails"],
    desc: "Subterranean jazz-age glamour; cocktails arrive dressed for the stage." },
  { name: "Happiness Forgets", type: "bar", area: "Hoxton", lat: 51.5266, lng: -0.0817, rating: 4.5,
    keywords: ["basement bar", "no fuss cocktails", "intimate"],
    desc: "'High end cocktails, low rent basement' — their words, and exactly right." },
  { name: "Callooh Callay", type: "bar", area: "Shoreditch", lat: 51.5266, lng: -0.0788, rating: 4.4,
    keywords: ["Narnia wardrobe", "playful", "cocktails"],
    desc: "Enter the back bar through a wardrobe. Jabberwocky-themed nonsense, expertly mixed." },
  { name: "Discount Suit Company", type: "bar", area: "Spitalfields", lat: 51.5169, lng: -0.0759, rating: 4.4,
    keywords: ["hidden basement", "low ceilings", "great value cocktails"],
    desc: "A former suit stockroom turned low-lit, low-ceilinged cocktail hideout." },
  { name: "Satan's Whiskers", type: "bar", area: "Bethnal Green", lat: 51.5277, lng: -0.0554, rating: 4.6,
    keywords: ["daily changing menu", "taxidermy", "hip hop", "serious drinks"],
    desc: "Cocktail menu changes daily; the taxidermy and hip-hop stay. East London's finest." },

  // ---- Hackney / Victoria Park / Docklands ----
  { name: "The Cock Tavern", type: "pub", area: "Hackney", lat: 51.5464, lng: -0.0561, rating: 4.4,
    keywords: ["cask & keg", "no music", "brewery below"],
    desc: "A drinkers' pub of the old school with a rotating army of casks." },
  { name: "The Chesham Arms", type: "pub", area: "Hackney", lat: 51.5478, lng: -0.0507, rating: 4.6,
    keywords: ["saved by locals", "garden", "backstreet", "perfect local"],
    desc: "Campaigned back from the dead by its neighbourhood — and you can taste the gratitude." },
  { name: "The Dove", type: "pub", area: "Broadway Market", lat: 51.5364, lng: -0.0605, rating: 4.3,
    keywords: ["belgian beer", "candlelit warren", "market days"],
    desc: "A candlelit warren with a Belgian beer list as long as the market queue outside." },
  { name: "The Royal Inn on the Park", type: "pub", area: "Victoria Park", lat: 51.5405, lng: -0.0455, rating: 4.3,
    keywords: ["park gates", "beer garden", "sunday roast", "dogs"],
    desc: "Right on Victoria Park's gates — the default finish line for an East London stroll." },
  { name: "The Palm Tree", type: "pub", area: "Mile End", lat: 51.5301, lng: -0.0344, rating: 4.4,
    keywords: ["east end time capsule", "cash only", "jazz nights", "canalside"],
    desc: "Alone by the canal, gold-flock wallpaper, cash only, live crooners. Unmissable." },
  { name: "The Grapes", type: "pub", area: "Limehouse", lat: 51.5093, lng: -0.0345, rating: 4.5,
    keywords: ["Gandalf's pub", "1583", "narrow riverside", "Dickens"],
    desc: "Part-owned by Sir Ian McKellen; a slim 1583 riverside survivor Dickens knew well." },
  { name: "The Prospect of Whitby", type: "pub", area: "Wapping", lat: 51.5066, lng: -0.0503, rating: 4.4,
    keywords: ["1520 — oldest riverside", "hangman's noose", "pewter bar"],
    desc: "London's oldest riverside tavern, complete with a noose swinging over the Thames." },
  { name: "The Town of Ramsgate", type: "pub", area: "Wapping", lat: 51.5044, lng: -0.0605, rating: 4.4,
    keywords: ["Execution Dock", "narrow", "river stairs", "history"],
    desc: "Beside the old Execution Dock stairs where pirates met the tide. Judge Jeffreys caught here." },
  { name: "The Captain Kidd", type: "pub", area: "Wapping", lat: 51.5049, lng: -0.0563, rating: 4.2,
    keywords: ["Sam Smith's", "river terrace", "warehouse"],
    desc: "A converted warehouse named for the pirate hanged nearby; big terrace on the water." },

  // ---- Islington / Angel / King's Cross ----
  { name: "The Drapers Arms", type: "pub", area: "Islington", lat: 51.5416, lng: -0.1055, rating: 4.4,
    keywords: ["gastropub", "handsome georgian", "sunday roast"],
    desc: "Islington's benchmark gastropub in a handsome Georgian townhouse." },
  { name: "The Pig and Butcher", type: "pub", area: "Islington", lat: 51.5364, lng: -0.1013, rating: 4.4,
    keywords: ["whole-beast butchery", "meat heaven", "smart"],
    desc: "On-site butchery and serious cooking; carnivore's Islington HQ." },
  { name: "The Camden Head", type: "pub", area: "Angel", lat: 51.5347, lng: -0.1029, rating: 4.2,
    keywords: ["Victorian glass", "comedy upstairs", "beer garden"],
    desc: "Etched glass and gas lamps outside, new comedians sweating upstairs." },
  { name: "The Earl of Essex", type: "pub", area: "Islington", lat: 51.5352, lng: -0.0977, rating: 4.4,
    keywords: ["beer board", "brews own", "garden"],
    desc: "A giant beer board runs the room; they brew some of it themselves." },
  { name: "The Charles Lamb", type: "pub", area: "Angel", lat: 51.5318, lng: -0.0983, rating: 4.5,
    keywords: ["backstreet gem", "small & friendly", "good food"],
    desc: "A tiny, warm-hearted backstreet local that everyone wishes was theirs." },
  { name: "The Island Queen", type: "pub", area: "Angel", lat: 51.5322, lng: -0.0972, rating: 4.4,
    keywords: ["soaring ceilings", "victorian mirrors", "near canal"],
    desc: "High Victorian theatre of a pub — vast mirrors, palms, and mahogany." },

  // ---- Camden / Kentish Town / Primrose Hill ----
  { name: "The Southampton Arms", type: "pub", area: "Kentish Town", lat: 51.5541, lng: -0.1445, rating: 4.7,
    keywords: ["ale & cider house", "cash only", "pork baps", "vinyl"],
    desc: "'Ale. Cider. Meat.' Small independent breweries only, cash only, perfection only." },
  { name: "The Pineapple", type: "pub", area: "Kentish Town", lat: 51.5510, lng: -0.1425, rating: 4.5,
    keywords: ["backstreet beauty", "saved by locals", "thai food", "cats"],
    desc: "Locals fought to save it in 2002 and won in eight days. You would too." },
  { name: "Tapping the Admiral", type: "pub", area: "Kentish Town", lat: 51.5450, lng: -0.1470, rating: 4.6,
    keywords: ["cask ale", "quiz night", "friendly", "CAMRA favourite"],
    desc: "Named for sailors sneaking rum from Nelson's preserving barrel. CAMRA royalty." },
  { name: "The Dublin Castle", type: "pub", area: "Camden", lat: 51.5390, lng: -0.1426, rating: 4.2,
    keywords: ["Madness started here", "live music", "sticky & loud"],
    desc: "The launchpad of Madness and a hundred Camden bands since. Gloriously unreconstructed." },
  { name: "The Hawley Arms", type: "pub", area: "Camden", lat: 51.5417, lng: -0.1461, rating: 4.2,
    keywords: ["Amy Winehouse's local", "rock'n'roll", "roof terrace"],
    desc: "Forever Amy's pub. Still the front room of Camden's music scene." },
  { name: "The Lock Tavern", type: "pub", area: "Camden", lat: 51.5433, lng: -0.1479, rating: 4.0,
    keywords: ["DJ sets", "roof garden", "weekend crowds"],
    desc: "Part pub, part venue, part rooftop hangout above the market swirl." },
  { name: "The Lansdowne", type: "pub", area: "Primrose Hill", lat: 51.5410, lng: -0.1541, rating: 4.3,
    keywords: ["gastropub", "pizzas", "celeb spotting"],
    desc: "Primrose Hill's laid-back gastropub of long standing; famous wood-fired pizzas." },
  { name: "The Princess of Wales", type: "pub", area: "Primrose Hill", lat: 51.5396, lng: -0.1568, rating: 4.3,
    keywords: ["near the hill", "sunday roast", "family friendly"],
    desc: "The natural descent from Primrose Hill's summit, roast dinner waiting." },
  { name: "The Engineer", type: "pub", area: "Primrose Hill", lat: 51.5388, lng: -0.1524, rating: 4.2,
    keywords: ["garden", "brunch", "canalside corner"],
    desc: "A Brunel-adjacent corner pub with one of the area's loveliest walled gardens." },

  // ---- Hampstead / Highgate ----
  { name: "The Holly Bush", type: "pub", area: "Hampstead", lat: 51.5566, lng: -0.1786, rating: 4.6,
    keywords: ["hilltop hideaway", "open fires", "low beams", "sunday roast"],
    desc: "Up a steep lane, behind an unchanged Georgian front: firelight, beams, bliss." },
  { name: "The Spaniards Inn", type: "pub", area: "Hampstead Heath", lat: 51.5670, lng: -0.1731, rating: 4.3,
    keywords: ["1585", "Dick Turpin", "big garden", "dogs everywhere"],
    desc: "Highwayman haunt on the Heath's edge; Keats wrote here, Turpin robbed here." },
  { name: "The Flask", type: "pub", area: "Highgate", lat: 51.5701, lng: -0.1503, rating: 4.4,
    keywords: ["village green", "haunted", "committee rooms", "winter fires"],
    desc: "Highgate village's 1663 heart, with ghosts in the cellar and poets in the snug." },
  { name: "The Flask (Hampstead)", type: "pub", area: "Hampstead", lat: 51.5561, lng: -0.1770, rating: 4.3,
    keywords: ["Youngs", "flask walk", "victorian screens"],
    desc: "Named for the spa-water flasks once filled nearby; a proper Young's local." },
  { name: "The Garden Gate", type: "pub", area: "Hampstead Heath", lat: 51.5541, lng: -0.1651, rating: 4.2,
    keywords: ["big garden", "post-heath pint", "burgers"],
    desc: "The classic reward after a Heath swim or stomp — a garden built for summer." },
  { name: "The Bull & Last", type: "pub", area: "Highgate", lat: 51.5556, lng: -0.1487, rating: 4.5,
    keywords: ["gastropub", "scotch eggs", "heath picnics"],
    desc: "Superb kitchen by the Heath; their scotch eggs have their own fan club." },

  // ---- North-east: Dalston / Stoke Newington ----
  { name: "Three Sheets", type: "bar", area: "Dalston", lat: 51.5546, lng: -0.0754, rating: 4.5,
    keywords: ["minimalist", "world-class cocktails", "small"],
    desc: "A plain little room making some of the best drinks in Europe. No theatrics needed." },
  { name: "The Auld Shillelagh", type: "pub", area: "Stoke Newington", lat: 51.5622, lng: -0.0793, rating: 4.5,
    keywords: ["best Guinness in London", "irish", "narrow", "live music"],
    desc: "Long, narrow, and pouring what many swear is the best Guinness outside Dublin." },
  { name: "The Jolly Butchers", type: "pub", area: "Stoke Newington", lat: 51.5578, lng: -0.0768, rating: 4.3,
    keywords: ["craft beer", "cask range", "buzzy"],
    desc: "Stoke Newington's craft-beer flagship — a deep, ever-rotating line-up." },

  // ---- West: Notting Hill / Maida Vale / Paddington / Kensington ----
  { name: "The Churchill Arms", type: "pub", area: "Kensington", lat: 51.5069, lng: -0.1946, rating: 4.6,
    keywords: ["flower-covered", "thai food", "Churchill shrine", "Fuller's"],
    desc: "Buried under 100+ hanging baskets; Winston memorabilia inside, great Thai out back." },
  { name: "The Windsor Castle", type: "pub", area: "Kensington", lat: 51.5075, lng: -0.1990, rating: 4.4,
    keywords: ["wooden snugs", "walled garden", "tiny doors"],
    desc: "Duck through tiny snug doors into 1835; the walled garden is a summer legend." },
  { name: "The Cow", type: "pub", area: "Westbourne Park", lat: 51.5182, lng: -0.1985, rating: 4.3,
    keywords: ["oysters & guinness", "notting hill set", "irish charm"],
    desc: "Tom Conran's fashionable take on the Irish boozer: oysters, stout, celebrity elbows." },
  { name: "The Prince Alfred", type: "pub", area: "Maida Vale", lat: 51.5230, lng: -0.1868, rating: 4.4,
    keywords: ["snob screens", "duck-under doors", "victorian showpiece"],
    desc: "Five snugs divided by original screens — you still duck between them. Astonishing." },
  { name: "The Warrington", type: "pub", area: "Maida Vale", lat: 51.5265, lng: -0.1857, rating: 4.2,
    keywords: ["art nouveau", "grand staircase", "faded glamour"],
    desc: "A flamboyant former hotel with a marble entrance most pubs would kill for." },
  { name: "The Victoria", type: "pub", area: "Paddington", lat: 51.5136, lng: -0.1783, rating: 4.4,
    keywords: ["Fuller's", "gilded mirrors", "Dickens lore"],
    desc: "Gilt, mirrors and fireplaces; Dickens reputedly wrote in the library upstairs." },

  // ---- Chelsea / Fulham / South Kensington ----
  { name: "The Anglesea Arms", type: "pub", area: "South Kensington", lat: 51.4906, lng: -0.1737, rating: 4.4,
    keywords: ["leafy terrace", "proper pub", "well-kept ales"],
    desc: "A dignified survivor among the stucco; terrace made for summer evenings." },
  { name: "The Surprise", type: "pub", area: "Chelsea", lat: 51.4859, lng: -0.1683, rating: 4.3,
    keywords: ["backstreet chelsea", "gastropub", "cosy"],
    desc: "Tucked in Chelsea's quiet grid — the surprise is finding it at all." },
  { name: "The Harwood Arms", type: "pub", area: "Fulham", lat: 51.4795, lng: -0.1961, rating: 4.6,
    keywords: ["Michelin star", "venison scotch egg", "game cookery"],
    desc: "London's first Michelin-starred pub; wild food cooked with reverence." },
  { name: "The White Horse", type: "pub", area: "Parsons Green", lat: 51.4718, lng: -0.2011, rating: 4.3,
    keywords: ["the sloaney pony", "beer festivals", "green-side terrace"],
    desc: "Nicknamed the Sloaney Pony, but the beer program is deadly serious." },

  // ---- Hammersmith / Chiswick / Richmond ----
  { name: "The Dove", type: "pub", area: "Hammersmith", lat: 51.4905, lng: -0.2352, rating: 4.5,
    keywords: ["smallest bar room", "riverside terrace", "Fuller's", "history"],
    desc: "Holds the record for Britain's smallest bar room; the river terrace is unbeatable." },
  { name: "The Blue Anchor", type: "pub", area: "Hammersmith", lat: 51.4901, lng: -0.2331, rating: 4.3,
    keywords: ["riverside", "rowers", "1722"],
    desc: "Watching rowers since 1722, right under Hammersmith Bridge." },
  { name: "The Old Ship", type: "pub", area: "Hammersmith", lat: 51.4899, lng: -0.2381, rating: 4.2,
    keywords: ["river terrace", "boat race views", "family friendly"],
    desc: "Prime Boat Race real estate with a big, easy terrace on the towpath." },
  { name: "The City Barge", type: "pub", area: "Chiswick", lat: 51.4874, lng: -0.2765, rating: 4.3,
    keywords: ["Beatles filmed here", "riverside", "kew reach"],
    desc: "The Beatles ran riot here in Help!; the tide still laps the doorstep." },
  { name: "The Bell & Crown", type: "pub", area: "Chiswick", lat: 51.4881, lng: -0.2799, rating: 4.3,
    keywords: ["Fuller's", "towpath", "conservatory"],
    desc: "A warm Fuller's local on the Strand-on-the-Green towpath." },
  { name: "The White Cross", type: "pub", area: "Richmond", lat: 51.4576, lng: -0.3053, rating: 4.3,
    keywords: ["floods at high tide", "riverside", "wellies provided"],
    desc: "So close to the Thames it regularly floods — check the tide table with your pint." },
  { name: "The White Swan", type: "pub", area: "Twickenham", lat: 51.4476, lng: -0.3222, rating: 4.4,
    keywords: ["riverside garden", "rugby days", "village feel"],
    desc: "A 17th-century gem on the Twickenham riverbank; garden faces Eel Pie Island." },

  // ---- South: Battersea / Clapham / Brixton / Wimbledon / Wandsworth ----
  { name: "The Alma", type: "pub", area: "Wandsworth", lat: 51.4614, lng: -0.1878, rating: 4.2,
    keywords: ["green tiles", "Youngs", "station corner"],
    desc: "A green-tiled Wandsworth beacon opposite the station — Young's heartland." },
  { name: "The Ship", type: "pub", area: "Wandsworth", lat: 51.4614, lng: -0.1927, rating: 4.2,
    keywords: ["riverside bbq", "big terrace", "summer crowds"],
    desc: "Sprawling Thames-side terrace with a barbecue running all summer." },
  { name: "The Falcon", type: "pub", area: "Battersea", lat: 51.4642, lng: -0.1682, rating: 4.1,
    keywords: ["longest bar counter", "victorian", "clapham junction"],
    desc: "Claims Britain's longest continuous bar counter — a horseshoe of Victorian mahogany." },
  { name: "The Windmill", type: "pub", area: "Clapham Common", lat: 51.4552, lng: -0.1494, rating: 4.1,
    keywords: ["on the common", "beer garden", "big sunday roast"],
    desc: "Right on the Common since 1729; summer evenings sprawl onto the grass." },
  { name: "The Canton Arms", type: "pub", area: "Stockwell", lat: 51.4740, lng: -0.1226, rating: 4.4,
    keywords: ["foie gras toastie", "gastropub", "no bookings"],
    desc: "Serious cooking, zero pretension, and a famously indulgent foie gras toastie." },
  { name: "The Crown & Anchor", type: "pub", area: "Brixton", lat: 51.4658, lng: -0.1136, rating: 4.3,
    keywords: ["craft taps", "pre-gig", "brixton buzz"],
    desc: "A long tap list and the obvious warm-up before the Academy." },
  { name: "The Sultan", type: "pub", area: "South Wimbledon", lat: 51.4166, lng: -0.1946, rating: 4.5,
    keywords: ["Hop Back brewery", "proper ale house", "CAMRA winner"],
    desc: "London's only Hop Back pub — Summer Lightning at its source-fresh best." },
  { name: "The Hand in Hand", type: "pub", area: "Wimbledon Common", lat: 51.4256, lng: -0.2308, rating: 4.4,
    keywords: ["common-side", "cottage pub", "post-walk pint"],
    desc: "A low-slung cottage pub on the Common's edge, made for muddy boots and dogs." },

  // ---- Greenwich / South-east ----
  { name: "The Cutty Sark Tavern", type: "pub", area: "Greenwich", lat: 51.4837, lng: -0.0037, rating: 4.4,
    keywords: ["georgian bow windows", "river views", "1795"],
    desc: "Georgian bow windows over a wide, quiet stretch of the Thames." },
  { name: "The Trafalgar Tavern", type: "pub", area: "Greenwich", lat: 51.4838, lng: -0.0087, rating: 4.3,
    keywords: ["whitebait dinners", "grand riverside", "Dickens"],
    desc: "Grand riverside ballroom of a pub, famous for Victorian whitebait feasts." },
  { name: "The Plume of Feathers", type: "pub", area: "Greenwich", lat: 51.4818, lng: 0.0000, rating: 4.3,
    keywords: ["1691", "meridian line", "park side"],
    desc: "Greenwich's oldest pub, sitting almost exactly on the Prime Meridian." },
  { name: "The Blythe Hill Tavern", type: "pub", area: "Forest Hill", lat: 51.4448, lng: -0.0356, rating: 4.7,
    keywords: ["perfect irish local", "guinness", "three snugs", "CAMRA legend"],
    desc: "A flawless three-room Irish local; regularly named among Britain's best pubs." },
  { name: "The Ivy House", type: "pub", area: "Nunhead", lat: 51.4636, lng: -0.0570, rating: 4.5,
    keywords: ["community owned", "1930s ballroom", "live music"],
    desc: "London's first community-owned pub, with a wood-panelled 1930s stage out back." },

  // ---- Bars: centre & south ----
  { name: "Gordon's Wine Bar", type: "bar", area: "Embankment", lat: 51.5080, lng: -0.1235, rating: 4.5,
    keywords: ["candlelit cellar", "1890", "cheese boards", "wine only"],
    desc: "London's oldest wine bar — a dripping candlelit cave under Villiers Street. No beer, no matter." },
  { name: "The American Bar at The Savoy", type: "bar", area: "Strand", lat: 51.5101, lng: -0.1205, rating: 4.5,
    keywords: ["legendary", "white lady", "piano", "dress up"],
    desc: "The grande dame of London cocktail bars, mixing since 1893." },
  { name: "Seed Library", type: "bar", area: "Shoreditch", lat: 51.5245, lng: -0.0786, rating: 4.3,
    keywords: ["analogue cocktails", "basement", "Mr Lyan"],
    desc: "Ryan Chetiyawardana's lo-fi basement bar in One Hundred Shoreditch." },
];
