#!/usr/bin/env node
/* ==========================================================================
   Fetch every pub & bar in Greater London from OpenStreetMap's Overpass API
   and write js/osm-data.js for the app.

   Usage:   node scripts/fetch-osm.mjs
   Needs:   curl on PATH (used for the HTTP call so system proxies just work)

   Data © OpenStreetMap contributors, ODbL — attribution is already in the
   map's credits line.
   ========================================================================== */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "js", "osm-data.js");

// 3600175342 = OSM relation 175342 (Greater London) as an Overpass area id
const QUERY = `
[out:json][timeout:180];
area(id:3600175342)->.london;
(
  nwr["amenity"="pub"](area.london);
  nwr["amenity"="bar"](area.london);
);
out center tags;
`;

// public Overpass instances — tried in order, with backoff, until one answers
const ENDPOINTS = [
  "https://overpass-api.de/api/interpreter",
  "https://overpass.kumi.systems/api/interpreter",
  "https://overpass.private.coffee/api/interpreter",
];

console.log("Querying Overpass for every pub & bar in Greater London…");
let json = null;
for (let attempt = 0; attempt < 6 && !json; attempt++) {
  const url = ENDPOINTS[attempt % ENDPOINTS.length];
  try {
    const raw = execFileSync(
      "curl",
      ["-sS", "--max-time", "300", url, "--data-urlencode", `data=${QUERY}`],
      { maxBuffer: 256 * 1024 * 1024, encoding: "utf8" }
    );
    json = JSON.parse(raw);
  } catch {
    const wait = 15 * (attempt + 1);
    console.log(`  ${url} is busy — retrying in ${wait}s…`);
    execFileSync("sleep", [String(wait)]);
  }
}
if (!json) {
  console.error("All Overpass endpoints are busy. Try again in a few minutes.");
  process.exit(1);
}

// turn useful OSM tags into the review-keyword chips the app displays
function keywordsFrom(tags) {
  const kws = [];
  const yes = (k) => tags[k] === "yes";
  if (yes("real_ale")) kws.push("cask ale");
  if (tags.microbrewery === "yes" || tags.craft === "brewery") kws.push("brews own");
  if (yes("outdoor_seating") || tags.beer_garden === "yes") kws.push("beer garden");
  if (yes("food") || tags.cuisine) kws.push("food");
  if (yes("live_music")) kws.push("live music");
  if (tags.dog === "yes" || tags.dogs === "yes") kws.push("dog friendly");
  if (tags.wheelchair === "yes") kws.push("step-free");
  if (yes("real_fire") || tags.fireplace === "yes") kws.push("open fire");
  if (tags.historic || (tags.start_date && tags.start_date < "1900")) kws.push("historic");
  return kws.slice(0, 4);
}

const seen = new Set();
const rows = [];
for (const el of json.elements) {
  const tags = el.tags || {};
  const name = (tags.name || "").trim();
  if (!name) continue; // unnamed = unfindable = skip
  const lat = el.lat ?? el.center?.lat;
  const lng = el.lon ?? el.center?.lon;
  if (lat == null || lng == null) continue;
  // OSM sometimes has a node AND a building way for the same pub — dedupe
  const key = `${name.toLowerCase()}|${lat.toFixed(3)}|${lng.toFixed(3)}`;
  if (seen.has(key)) continue;
  seen.add(key);
  rows.push({
    name,
    type: tags.amenity === "bar" ? "bar" : "pub",
    lat: +lat.toFixed(5),
    lng: +lng.toFixed(5),
    keywords: keywordsFrom(tags),
  });
}
rows.sort((a, b) => a.name.localeCompare(b.name));

const header =
  `/* Generated by scripts/fetch-osm.mjs on ${json.osm3s?.timestamp_osm_base || "unknown date"}.\n` +
  `   Every named pub & bar in Greater London.\n` +
  `   Data © OpenStreetMap contributors, ODbL. Do not edit by hand — re-run the script. */\n`;
writeFileSync(OUT, header + "const OSM_PUBS = " + JSON.stringify(rows) + ";\n");
console.log(`Wrote ${rows.length} pubs & bars to ${OUT}`);
